[package]
name = "sa-token-plugin-oauth2"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Runtime-scoped OAuth2 plugin for sa-token-rust"

[dependencies]
async-trait = { workspace = true }
sa-token-adapter = { version = "0.1.18", path = "../../sa-token-adapter" }
sa-token-core = { version = "0.1.18", path = "../../sa-token-core" }

[dev-dependencies]
sa-token-storage-memory = { version = "0.1.18", path = "../../sa-token-storage/sa-token-storage-memory" }
tokio = { workspace = true }
